image:
  file: .gitpod.Dockerfile

ports:
  # WordPress server
  - port: 8000
    onOpen: open-preview
  # MySQL server
  - port: 3306
    onOpen: ignore

tasks:
  - init: >
      mysql -u root -e "create database wordpress" &&
      mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'wordpress';" &&
      composer install
  - command: >
      php -S 0.0.0.0:8000

vscode:
  extensions:
    - ms-azuretools.vscode-docker
